name: http_service
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/nikitakozlovcoder/dart_http_service

environment:
  sdk: '>=2.18.1 <3.0.0'
 
dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
