name: injectable_http_service
description: Simple http service to use with injectable.
version: 1.0.1
repository: https://github.com/nikitakozlovcoder/dart_http_service

environment:
  sdk: '>=2.18.1 <3.0.0'
 
dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
